# Generated by Django 5.2.6 on 2025-09-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_soccer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='player',
            field=models.IntegerField(default=0),
        ),
    ]
