# Generated by Django 5.2.6 on 2025-09-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_soccer_app', '0002_word_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='player',
            new_name='player_id',
        ),
    ]
