# Generated by Django 5.2.6 on 2025-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_soccer_app', '0003_rename_player_word_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_in_dict',
            field=models.BooleanField(default=False),
        ),
    ]
