# Generated by Django 5.2 on 2025-09-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_soccer_app', '0004_word_is_in_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=False)),
                ('goals_player1', models.IntegerField(default=0)),
                ('goals_player2', models.IntegerField(default=0)),
                ('has_player1_yellow_card', models.BooleanField(default=False)),
                ('has_player2_yellow_card', models.BooleanField(default=False)),
                ('red_cards_player1', models.IntegerField(default=0)),
                ('red_cards_player2', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='player_id',
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word_soccer_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='is_in_dict',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='word_soccer_app.player')),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='word_soccer_app.player')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word_soccer_app.matchstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_progress', models.BooleanField(default=False)),
                ('letters_player1', models.IntegerField(default=0)),
                ('letters_player2', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_soccer_app.match')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word_soccer_app.round'),
        ),
    ]
